name: Build LaTex Doc
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install texlive
        run: sudo apt install texlive-base texlive-latex-extra
      - name: Build PDF
        run: pdflatex resume.tex -o resume.pdf
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: build doc"
          branch: build
          title: '[CI] Generate PDF'
